# - name: variables from promt
#   hosts: web
#   vars_prompt:
#   - name: COURSE
#     prompt: Please enter the course name
#     private: false #not confidentaial
#   - name: TRAINER
#     prompt: Please enter the trainer name
#     private: false #not confidentaial
#   tasks:
#   - name: Print the inforamtion
#     ansible.builtin.debug:
#       msg: "Hi, I am learning {{COURSE}}, Trainer: {{TRAINER}}"

- name: Vars from prompt
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: Enter the course name
  - name: Learner
    prompt: enter the course name
  tasks:
  - name: print the inforamtion
    ansible.builtin.debug:
      msg: "Hi , im learning {{COURSE}}, Learner {{Learner}}"