- name: variables from promt
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: Please enter the course name
  - name: TRAINER
    prompt: Please enter the trainer name
  tasks:
  - name: Print the inforamtion
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Trainer: {{TRAINER}}"